.PHONY: install dev start install-stg install-dev install-prod

install-stg:
	python ./install_helper.py stg

install-dev:
	python ./install_helper.py dev

install-prod:
	python ./install_helper.py prod

dev:
	npm run dev

start: dev
