name: 'Publish alpha releases'

on:
  push:
    branches:
      - main

jobs:
  publish-react:
    name: Publish React to NPM (Alpha)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Set hash and version variable
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(npm view ./ version)" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(npm view ./ version)-alpha.$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build React package
        run: |
          npm ci
          npm run build:react:alpha

      - name: Publish React package
        working-directory: ./packages/react
        run: |
          npm version ${{ env.VERSION }}-alpha.${{ env.COMMIT_HASH }} --no-git-tag-version
          npm publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-vanilla:
    name: Publish Vanilla to NPM (Alpha)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Set hash and version variable
        run: |
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "VERSION=$(node -p "require('./packages/vanilla/package.json').version")" >> $GITHUB_ENV

      - name: Build Vanilla package
        run: echo "Skipping for testing purposes"
        # run: |
        #   npm ci
        #   npm run build:vanilla:alpha

      - name: Publish Vanilla package
        working-directory: ./packages/vanilla
        run: |
          echo "Skipping for testing purposes"
        # run: |
        #   npm version ${{ env.RELEASE_VERSION }} --no-git-tag-version
        #   npm publish --tag alpha --access public
        # env:
        #   NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
