name: 'Publish stable release'

on:
  release:
    types: [created]

jobs:
  publish:
    name: 🚀 Publishing to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Build package
        run: |
          npm ci
          npm run build

      - name: Publish package
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
