name: 'Publish stable release'

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: |
          npm ci

      - name: Publish package (alpha)
        if: 'github.event.release.prerelease'
        run: |
          npm run build:alpha
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          npm version ${{ github.ref_name }} --no-git-tag-version
          npm publish --tag alpha --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish package (stable)
        if: '!github.event.release.prerelease'
        run: |
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
